### ISSUE TITLE
Progress HUD doesn't respect status bar appearance

### ISSUE THREAD

**Issue by Dreddik** [krimpedance/KRProgressHUD#7]
For example, hidden status bar appeared with progress hud

**Comment by krimpedance** [comment]
Thanks :)
I fixed now. (0fd175e)

**Comment by mamouneyya** [comment]
Still not 100% resolved. While it respects now weather the bar hidden or no, it still doesn't respect `preferredStatusBarStyle()` when `UIViewControllerBasedStatusBarAppearance` is enabled.

**Comment by mamouneyya** [comment]
Adding this to KRProgressHUDViewController solves the issue:

```
override func preferredStatusBarStyle() -> UIStatusBarStyle {
    var statusBarStyle = UIStatusBarStyle.Default
    guard let vc = UIApplication.topViewController() else { return statusBarStyle }
    if !vc.isKindOfClass(KRProgressHUDViewController) {
        statusBarStyle = vc.preferredStatusBarStyle()
    }
    return statusBarStyle
}
```

I can make a PR for you, if you like...

**Comment by mamouneyya** [comment]
Actually, this doesn't seem to work properly in all cases.. as the library seems to create a new window sometimes? (In that case, `topViewController` of the current `keyWindow` will be always KRProgressHUDViewController.. ending with the default value returned from the above function)

<img width="383" alt="screen shot - - at" src="https://cloud.githubusercontent.com/assets/212818/17834050/eff7748a-6738-11e6-94af-10a1aed244d4.png">

**Comment by krimpedance** [comment]
Hi, @mamouneyya.
Thank you for your pointing out.
I published version 1.6.1 that fixed it.

> Actually, this doesn't seem to work properly in .....
KRProgressHUD replaces keyWindow at `dismiss()`.
Therefore `topViewController` moves right.
`isKindOfClass()` is insurance.

**Comment by mamouneyya** [comment]
I actually added the last comment because I came to that case while debugging, however I still cannot get a clear scenario to reproduce it..
